# This is a sample config file that points to a solr server for each environment
development:
  url: <%= ENV['SOLR_URL'] || 'http://127.0.0.1:8983/solr/development' %>
test:
  url: <%= ENV['SOLR_URL'] || 'http://127.0.0.1:8983/solr/test' %>
production:
  url: <%= ENV['SOLR_URL'] || 'http://your.production.server:8080/bl_solr/core0' %>
